name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 Features'
      collapse-after: 5
      label: 'feat'
    - title: 'Fixes'
      collapse-after: 5
      label: 'fix'
    - title: 'Documentation'
      collapse-after: 5
      label: 'docs'
    - title: 'Maintenance'
      collapse-after: 5
      labels:
          - 'chore'
          - 'ci'
          - 'cleanup'
          - 'perf'
          - 'refactor'
          - 'style'
          - 'test'

autolabeler:
    - label: 'feat'
      title: 
        - '/^feat:/'
    - label: 'fix'
      title: 
        - '/^fix:/'
    - label: 'docs'
      title: 
        - '/^docs:/'
    - label: 'chore'
      title: 
        - '/^chore:/'
    - label: 'ci'
      title: 
        - '/^ci:/'
    - label: 'cleanup'
      title: 
        - '/^cleanup:/'
    - label: 'perf'
      title: 
        - '/^perf:/'
    - label: 'refactor'
      title: 
        - '/^refactor:/'
    - label: 'style'
      title: 
        - '/^style:/'
    - label: 'test'
      title: 
        - '/^test:/'

template: |
    ## What's Changed
    $CHANGES
