apiVersion: v2
name: cryostat
description: Securely manage JFR recordings for your containerized Java workloads

type: application

version: "1.0.1"

kubeVersion: ">= 1.25.0-0"

appVersion: "3.0.1"

home: "https://cryostat.io"

icon: "https://raw.githubusercontent.com/cryostatio/cryostat-helm/main/docs/images/cryostat-icon.svg"

keywords:
- flightrecorder
- java
- jdk
- jfr
- jmc
- missioncontrol
- monitoring
- profiling
- diagnostic

sources:
- https://github.com/cryostatio/cryostat3
- https://github.com/cryostatio/cryostat-core
- https://github.com/cryostatio/cryostat-web
- https://github.com/cryostatio/jfr-datasource
- https://github.com/cryostatio/cryostat-grafana-dashboard
- https://github.com/cryostatio/cryostat-db
- https://github.com/cryostatio/cryostat-storage
- https://github.com/cryostatio/openshift-oauth-proxy
- https://github.com/oauth2-proxy/oauth2-proxy

maintainers:
- name: The Cryostat Community
  url: https://groups.google.com/g/cryostat-development
