apiVersion: v2
name: cryostat
description: Securely manage JFR recordings for your containerized Java workloads

type: application

version: "0.2.0"

<<<<<<< HEAD
appVersion: "2.2.0"
=======
kubeVersion: ">= 1.19.0"

appVersion: "latest"
>>>>>>> 6790773 (chore(chart): specify kubeVersion constraints (#47))

home: "https://cryostat.io"

icon: "https://raw.githubusercontent.com/cryostatio/cryostat-helm/main/docs/images/cryostat-icon.svg"

keywords:
- flightrecorder
- java
- jdk
- jfr
- jmc
- missioncontrol
- monitoring
- profiling
- diagnostic

sources:
- https://github.com/cryostatio/cryostat
- https://github.com/cryostatio/cryostat-core
- https://github.com/cryostatio/cryostat-web
- https://github.com/cryostatio/jfr-datasource
- https://github.com/cryostatio/cryostat-grafana-dashboard

maintainers:
- name: The Cryostat Community
  url: https://groups.google.com/g/cryostat-development
