{{/*
   Alpha Configuration is not used with OpenShift OAuth Proxy
*/}}
{{- if not (.Values.authentication.openshift).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alpha-config
  labels:
    {{- include "cryostat.labels" . | nindent 4 }}
data:
  alpha_config.yaml: |-
    server:
      BindAddress: http://0.0.0.0:4180
      {{- if .Values.oauth2Proxy.service.tls.enableSelfSigned }}
      SecureBindAddress: https://0.0.0.0:8443
      {{- end}}
      TLS:
        Key:
          fromFile: /etc/tls/private/KEY
        Cert:
          fromFile: /etc/tls/private/CERT
    upstreamConfig:
      proxyRawPath: true
      upstreams:
        - id: cryostat
          path: /
          uri: http://localhost:8181
        - id: grafana
          path: /grafana/
          uri: http://localhost:3000
    providers:
      - id: dummy
        name: Unused - Sign In Below
        clientId: CLIENT_ID
        clientSecret: CLIENT_SECRET
        provider: google
{{- end }}
