version: "3"
services:
  auth:
    depends_on:
      cryostat:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
    image: ${OAUTH2_PROXY_IMAGE:-quay.io/oauth2-proxy/oauth2-proxy:latest}
    ports:
      - "8080:8080"
    hostname: auth
    labels:
      kompose.service.expose: "auth"
    environment:
      OAUTH2_PROXY_HTPASSWD_FILE: ./auth_proxy_htpasswd
