{{- if empty .Values.authentication.cookieSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cookie-secret
type: Opaque
data:
  COOKIE_SECRET: {{ include "cryostat.cookieSecret" . }}
{{- end -}}
