{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-cookie-secret" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cookie-secret
type: Opaque
{{ if $secret -}}
data:
  COOKIE_SECRET: {{ $secret.data.COOKIE_SECRET }}
{{ else -}}
stringData:
  COOKIE_SECRET: {{ randAlphaNum 32 }}
{{ end }}
