{{- $fullName := include "cryostat.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-db
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
    component: db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
  selector:
    {{- include "cryostat.selectorLabels" $ | nindent 4 }}
    component: db
