{{- if ((.Values.networkPolicy.ingress).enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-internal-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "cryostat.selectorLabels" $ | nindent 6 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "cryostat.selectorLabels" $ | nindent 12 }}
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
