{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-persistent-volumeclaim
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{- end }}
