{{- $fullName := include "cryostat.fullname" . -}}
---
{{- if gt (int (.Values.reports).replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-reports
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
    app.kubernetes.io/component: reports
spec:
  type: {{ .Values.reports.service.type }}
  ports:
    - port: {{ .Values.reports.service.httpPort }}
      # TODO this should be https/8443
      targetPort: 4180
  selector:
    {{- include "cryostat.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: reports
{{- end -}}
