{{- $fullName := include "cryostat.fullname" . -}}
---
{{- if gt (int (.Values.reports).replicas) 0 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryostat.deploymentName" . }}-reports
  labels:
    {{- include "cryostat.labels" . | nindent 4 }}
    app.kubernetes.io/component: reports
spec:
  replicas: {{ (.Values.reports).replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "cryostat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reports
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reports.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryostat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: reports
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- include "cryostat.reportsAuthProxy" . | nindent 8 }}
        - name: {{ printf "%s-%s" .Chart.Name "reports" }}
          securityContext:
            {{- toYaml (.Values.reports).securityContext | nindent 12 }}
          image: "{{ (.Values.reports).image.repository }}{{ include "cryostat.imageSeparator" (.Values.reports).image.tag }}{{ (.Values.reports).image.tag }}"
          imagePullPolicy: {{ (.Values.reports).image.pullPolicy }}
          env:
          - name: QUARKUS_HTTP_HOST
            value: localhost
          - name: QUARKUS_LOG_LEVEL
            value: {{ .Values.reports.debug.log.level }}
          - name: QUARKUS_HTTP_PORT
            value: "{{ .Values.reports.service.httpPort }}"
          {{- if and ((include "cryostat.certManager.enabled" .) | eq "true") (empty (.Values.storage.provider).url) }}
          - name: QUARKUS_S3_AWS_CREDENTIALS_TYPE
            value: "anonymous"
          - name: CRYOSTAT_STORAGE_TLS_CA_PATH
            value: "/etc/storage-tls/ca.crt"
          - name: CRYOSTAT_STORAGE_TLS_CERT_PATH
            value: "/etc/storage-tls/tls.crt"
          {{- end }}
          {{- with (.Values.reports.config).extra.envVars }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with (.Values.reports.config).extra.envSources }}
          envFrom:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.reports.service.httpPort }}
            protocol: TCP
          {{- if and ((include "cryostat.certManager.enabled" .) | eq "true") (empty (.Values.storage.provider).url) }}
          volumeMounts:
          - name: storage-tls
            mountPath: /etc/storage-tls
            readOnly: true
          {{- end }}
          startupProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.reports.service.httpPort }}
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 9
          livenessProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.reports.service.httpPort }}
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 2
          resources:
            {{- toYaml (.Values.reports).resources | nindent 12 }}
      {{- with (default .Values.nodeSelector .Values.reports.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.affinity .Values.reports.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.tolerations .Values.reports.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-reports-secret
        secret:
          defaultMode: 0444
          secretName: {{ .Release.Name }}-reports-secret
      {{- if (.Values.authentication.openshift).enabled }}
      - name: {{ .Release.Name }}-proxy-tls
        secret:
          secretName: {{ .Release.Name }}-proxy-tls
      {{- else if .Values.oauth2Proxy.tls.selfSigned.enabled }}
      - name: {{ .Release.Name }}-oauth2proxy-reports-tls
        secret:
          secretName: {{ .Release.Name }}-oauth2proxy-reports-tls
      {{- end }}
      {{- if (include "cryostat.certManager.enabled" .) | eq "true" }}
      - name: reports-tls
        secret:
          secretName: {{ include "cryostat.tls.reports.secretName" . }}
      {{- if (empty (.Values.storage.provider).url) }}
      - name: storage-tls
        secret:
          secretName: {{ include "cryostat.tls.storage.secretName" . }}
          defaultMode: 0440
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
      {{- end }}
      {{- end }}
{{- end -}}
