{{- $fullName := include "cryostat.fullname" . -}}
---
{{- if gt (int (.Values.reports).replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-reports
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.reports.service.type }}
  ports:
    - port: {{ .Values.reports.service.httpPort }}
  selector:
    {{- include "cryostat.selectorLabels" $ | nindent 4 }}
    component: reports
{{- end -}}
