{{- $fullName := include "cryostat.fullname" . -}}
---
{{- if gt (int (.Values.reports).replicas) 0 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryostat.deploymentName" . }}-reports
  labels:
    {{- include "cryostat.labels" . | nindent 4 }}
    app.kubernetes.io/component: reports
spec:
  replicas: {{ (.Values.reports).replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "cryostat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reports
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryostat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: reports
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryostat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ printf "%s-%s" .Chart.Name "reports" }}
          securityContext:
            {{- toYaml (.Values.reports).securityContext | nindent 12 }}
          image: "{{ (.Values.reports).image.repository }}:{{ (.Values.reports).image.tag }}"
          imagePullPolicy: {{ (.Values.reports).image.pullPolicy }}
          env:
            - name: QUARKUS_HTTP_PORT
              value: "{{ .Values.reports.service.httpPort }}"
          ports:
            - containerPort: {{ .Values.reports.service.httpPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.reports.service.httpPort }}
            periodSeconds: 10
            failureThreshold: 9
          livenessProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.reports.service.httpPort }}
            periodSeconds: 10
            failureThreshold: 2
          resources:
            {{- toYaml (.Values.reports).resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
