{{- if (and (not (.Values.authentication.openshift).enabled) (.Values.oauth2Proxy.tls.selfSigned.enabled)) }}
{{- $fullName := include "cryostat.fullname" . }}
{{- $cert := genSelfSignedCert (printf "%s-reports" $fullName) nil nil 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth2proxy-reports-tls
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
type: Opaque
immutable: true
data:
  cert: {{ $cert.Cert | b64enc }}
  key: {{ $cert.Key | b64enc }}
{{- end -}}
