name: submodule

on:
  push:
    branches:
      - gh-pages

defaults:
  run:
    shell: bash

jobs:
  update-submodule:
    if: ${{ github.repository_owner == 'cryostatio' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: cryostatio/cryostatio.github.io
        token: "${{ secrets.SUBMODULE_TOKEN }}"
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Update submodule to latest commit
      run: |
        git submodule update --init
        git submodule update --remote
    - name: Commit and push submodule
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add --all
        git_hash="$(git rev-parse --short :helm-charts)"
        git commit -S -m "build(helm-charts): update submodule to $git_hash" || echo "No changes to commit"
        git push
